apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: result-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/result:d26f9464ffcfe9ad440f0152708ffe8a85b417f8
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: app-cm


---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  selector:
    app: result-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/vote:d26f9464ffcfe9ad440f0152708ffe8a85b417f8
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: app-cm

---
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: 427613144745.dkr.ecr.us-east-1.amazonaws.com/worker:d26f9464ffcfe9ad440f0152708ffe8a85b417f8
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: app-cm

---
apiVersion: v1
kind: Service
metadata:
  name: worker-app
spec:
  selector:
    app: worker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


